// Role permissions configuration
const ROLE_PERMISSIONS = {
  'super user': new Set([
    'Accueil',
    'Cours',
    'Quiz',
    'Présence',
    'Emploi du temps',
    'Générer documents',
    'Documents',
    'Demandes',
    'Planificateur',
    'Filières',
    'Compétences',
    'Secteurs',
    'Groupes',
    'Modules',
    'Paramètres',
    'Stagiaires',
    'Formateurs',
  ]),
  admin: new Set([
    'Accueil',
    'Présence',
    'Documents',
    'Demandes',
    'Planificateur',
    'Filières',
    'Compétences',
    'Secteurs',
    'Groupes',
    'Modules',
    'Stagiaires',
    'Formateurs',
  ]),
  trainer: new Set([
    'Accueil',
    'Cours',
    'Quiz',
    'Stagiaires',
    'Présence',
    'Emploi du temps',
    'Documents',
  ]),
  trainee: new Set(['Accueil', 'Cours', 'Quiz', 'Emploi du temps', 'Documents']),
};

export { ROLE_PERMISSIONS };
